version: '3.5'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "../container/nginx/conf/docker_proxy.conf:/etc/nginx/conf.d/docker_proxy.conf:ro"
      - "../container/nginx/certs:/etc/nginx/certs:ro"
      - "../container/nginx/vhosts:/etc/nginx/vhost.d"
      - "../container/nginx/html:/usr/share/nginx/html"
      - "../container/nginx/htpasswd:/etc/nginx/htpasswd"
    ports:
      - "${PROXY_PORT}:80"
    restart: always

  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../container/portainer/data:/data"
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: portainer.${BASE_DOMAIN}
    restart: always

  logstash:
    image: svenwltr/console-gelf-server
    container_name: logstash
    links: []
    volumes: []
    ports:
      - "12201:12201/udp"
    restart: always

networks:
  default:
    driver: bridge
    name: proxy
