version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "../container/nginx/conf/docker_proxy.conf:/etc/nginx/conf.d/docker_proxy.conf:ro"
      - "../container/nginx/certs:/etc/nginx/certs:ro"
      - "../container/nginx/vhosts:/etc/nginx/vhost.d"
      - "../container/nginx/vhosts_base/docker-ui_location:/etc/nginx/vhost.d/docker-ui.${BASE_DOMAIN}_location"
      - "../container/nginx/html:/usr/share/nginx/html"
      - "../container/nginx/htpasswd/kibana:/etc/nginx/htpasswd/kibana.${BASE_DOMAIN}"
      - "../container/nginx/htpasswd/docker-ui:/etc/nginx/htpasswd/docker-ui.${BASE_DOMAIN}"
      - "../container/nginx/update-htpasswd.sh:/update-htpasswd.sh"
    ports:
      - "${PROXY_PORT}:80"
    networks:
      - "frontend-tier"

  ui:
    image: uifd/ui-for-docker
    container_name: ui-for-docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: docker-ui.${BASE_DOMAIN}
    networks:
      - "frontend-tier"

  elk-logstash:
    image: svenwltr/console-gelf-server
    links: []
    volumes: []
    ports:
      - "12201:12201/udp"

networks:
  frontend-tier:
    external:
      name: proxy
