version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    depends_on:
      - logger
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "../container/nginx/docker_proxy.conf:/etc/nginx/conf.d/docker_proxy.conf:ro"
      - "../container/nginx/docker-ui.local.orangehive.de_location:/etc/nginx/vhost.d/docker-ui.local.orangehive.de_location:ro"
    ports:
      - "${PROXY_PORT}:80"
    networks:
      - "frontend-tier"

  ui:
    image: uifd/ui-for-docker
    container_name: ui-for-docker
    depends_on:
      - logger
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: docker-ui.${BASE_DOMAIN}
    networks:
      - "frontend-tier"

  logger:
    image: graylog2/allinone
    container_name: logger
    ports:
      - "12201:12201/udp"
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: graylog.${BASE_DOMAIN}
      GRAYLOG_PASSWORD: ${GRAYLOG_ADMIN_PASSWORD}
    networks:
      - "frontend-tier"

networks:
  frontend-tier:
    external:
      name: proxy

