version: '2'
services:
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - "nginx"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../container/nginx/certs:/etc/nginx/certs:rw"
    volumes_from:
      - "nginx"
    networks:
      - "frontend-tier"


